import type { Metadata } from 'next';
import { Mulish } from 'next/font/google';

import './globals.css';

import styles from './style.module.scss';

import RouteNavigator from '@atoms/RouteNavigator';
import Navbar from '@organisms/Navbar';
import Footer from '@organisms/Footer';
import bindClass from '@helpers/bindClass';

import IndexContextProvider from '@contexts/index';

const mulish = Mulish({
  weight: ['400', '700', '800'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={bindClass(mulish.className, styles['layout'])}>
        <IndexContextProvider>
          <Navbar />

          <main className={styles['layout__container']}>{children}</main>

          <Footer />
        </IndexContextProvider>
      </body>

      <RouteNavigator />
    </html>
  );
}
